on:
  issues:
    types:
      - opened

jobs:
  automation_update:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Configuration Environment
        run: |
          git config --global user.name "Sam Chen"
          git config --global user.email "silent198214@gmail.com"
      - name: Update rbl list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          if grep -qxF $ISSUE_BODY ./rbl-ip_home.txt
          then
            gh issue edit $ISSUE_URL --add-label "duplicate"
          else
            gh issue edit $ISSUE_URL --add-label "added"
            echo $ISSUE_BODY >> ./rbl-ip_home.txt
            git add .
            git commit -m "Auto updating rbl list"
            git push
          fi
          gh issue close $ISSUE_URL
        
          
          
